# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AbtastyCli < Formula
  desc ""
  homepage "https://github.com/flagship-io/abtasty-cli"
  version "1.0.7"

  on_macos do
    url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.7/abtasty-cli_1.0.7_darwin_all.tar.gz"
    sha256 "88f03b198e82dcbdf3e7f6191f181eec93ba167150dfbf33814114c1695d62cb"

    def install
      bin.install "abtasty-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.7/abtasty-cli_1.0.7_linux_amd64.tar.gz"
        sha256 "c77c2719bb2051fc36d222596fff2bf3c28819e603ad1249688c9abcf49ff2d2"

        def install
          bin.install "abtasty-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.7/abtasty-cli_1.0.7_linux_arm64.tar.gz"
        sha256 "99810458e305b6b15a7a5741848aa6daaf29868b5cd1e1dd6c4ec13b995aa199"

        def install
          bin.install "abtasty-cli"
        end
      end
    end
  end
end
