# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AbtastyCli < Formula
  desc ""
  homepage "https://github.com/flagship-io/abtasty-cli"
  version "1.0.3"

  on_macos do
    url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.3/abtasty-cli_1.0.3_darwin_all.tar.gz"
    sha256 "5c83ec2fecec0cf11ca4459a4ffb83b5fcb9fd95a7f6b9d1f960a079baca896e"

    def install
      bin.install "abtasty-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.3/abtasty-cli_1.0.3_linux_amd64.tar.gz"
        sha256 "b5efeca304cd75a13c72b220e71c7402eb101c66ba8952648a450be6bceb50d8"

        def install
          bin.install "abtasty-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flagship-io/abtasty-cli/releases/download/v1.0.3/abtasty-cli_1.0.3_linux_arm64.tar.gz"
        sha256 "f4785b2c620a3d2c2bcfd72397ab70f7686c8d82b104c3c01e9c95b0923a24f0"

        def install
          bin.install "abtasty-cli"
        end
      end
    end
  end
end
